{
  inputs,
  pkgs,
  ...
}: {
  config = {
    environment.systemPackages = with pkgs; [
      inputs.nix-alien.packages.${pkgs.system}.nix-alien
      inputs.fix-python.packages.${pkgs.system}.default
      inputs.alejandra.defaultPackage.${pkgs.system}
      inputs.orb.packages.${pkgs.system}.default
      networkmanagerapplet
      nix-output-monitor
      google-java-format
      swaylock-effects
      docker-compose
      signal-desktop
      brightnessctl
      libqalculate
      tree-sitter
      arduino-ide
      arduino-cli
      protonup-ng
      ytmdesktop
      pulsemixer
      obs-studio
      steam-run
      libnotify
      python311
      fastfetch
      html-tidy
      nodejs_22
      r2modman
      quickemu
      onedrive
      autoconf
      minikube
      typstfmt
      libclang
      typstyle
      vesktop
      nyancat
      todoist
      openssh
      killall
      openvpn
      ripgrep
      conjure
      pipenv
      gradle
      choose
      awscli
      antlr
      typst
      dpkg
      gdal
      qgis
      htop
      ouch
      tldr
      pipx
      jdk
      gcc
      bat
      feh
      nvd
      bc
      fd
      jq
      sd

      # Wayland
      sway-contrib.grimshot
      wl-clip-persist
      wl-clipboard
      hyprpicker
      hyprshot
      cliphist
      swappy
      slurp
      grim
      swww
    ];
  };
}
